export const users = [{
    "id": 1,
    "username": "jgregan0",
    "NSS": "1847460845",
    "role": "USER",
    "password": "xI4?4x!t",
    "boutique": "Alger"
  }, {
    "id": 2,
    "username": "ebidewell1",
    "NSS": "2298469737",
    "role": "USER",
    "password": "mO8&NnfLMd",
    "boutique": "Alger"
  }, {
    "id": 3,
    "username": "slouch2",
    "NSS": "3968598383",
    "role": "USER",
    "password": "qV4\\cR$d\\AvwQ<cW",
    "boutique": "Alger"
  }, {
    "id": 4,
    "username": "mcoston3",
    "NSS": "4609299740",
    "role": "USER",
    "password": "nZ4%rd4W",
    "boutique": "Batna"
  }, {
    "id": 5,
    "username": "wbrando4",
    "NSS": "1519986345",
    "role": "Admin",
    "password": "oX0@Yka)",
    "boutique": "Alger"
  }, {
    "id": 6,
    "username": "scoils5",
    "NSS": "7800278413",
    "role": "USER",
    "password": "jZ7,E<a%no(H&r",
    "boutique": "Alger"
  }, {
    "id": 7,
    "username": "dibbotson6",
    "NSS": "3534415909",
    "role": "USER",
    "password": "dH7~E1>&",
    "boutique": "Alger"
  }, {
    "id": 8,
    "username": "jbroadfoot7",
    "NSS": "8217554544",
    "role": "USER",
    "password": "lT3`O=H>",
    "boutique": "Alger"
  }, {
    "id": 9,
    "username": "lmckean8",
    "NSS": "2499448800",
    "role": "USER",
    "password": "gF9{B*gXgoJ+(lR",
    "boutique": "Alger"
  }, {
    "id": 10,
    "username": "enavarro9",
    "NSS": "6891318450",
    "role": "USER",
    "password": "pJ9,.UI2",
    "boutique": "Alger"
  }]
  